name: Build Site

on:
  pull_request:
    branches:
      - gaia

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # ou la version de Ruby que vous utilisez

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ./

      - name: Build Site
        run: bundle exec jekyll build
        working-directory: ./

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: site-build
          path: ./_site
